package cx.aswin.boxlore.core.designsystem.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

/** Authored classic palette from the boxlore brand kit. */
internal object ClassicBrandColors {
    val light = lightColorScheme(
        primary = Color(0xFF5145D8),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFE5E0FF),
        onPrimaryContainer = Color(0xFF261D58),
        secondary = Color(0xFF55647C),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFDFE6F2),
        onSecondaryContainer = Color(0xFF202D42),
        tertiary = Color(0xFF397B6D),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFCDEDE1),
        onTertiaryContainer = Color(0xFF123C32),
        error = Color(0xFFB3261E),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFF9DEDC),
        onErrorContainer = Color(0xFF410E0B),
        background = Color(0xFFF8F8FB),
        onBackground = Color(0xFF1A1B23),
        surface = Color(0xFFF8F8FB),
        onSurface = Color(0xFF1A1B23),
        surfaceVariant = Color(0xFFE5E3EE),
        onSurfaceVariant = Color(0xFF494854),
        outline = Color(0xFF797783),
        outlineVariant = Color(0xFFCBC7D4),
        inverseSurface = Color(0xFF2E3038),
        inverseOnSurface = Color(0xFFF1F0F6),
        inversePrimary = Color(0xFF9C8CFF),
        surfaceTint = Color(0xFF5145D8),
        scrim = Color(0xFF000000),
        surfaceDim = Color(0xFFDDDDE5),
        surfaceBright = Color(0xFFFAFAFE),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF2F2F7),
        surfaceContainer = Color(0xFFEDEDF4),
        surfaceContainerHigh = Color(0xFFE7E7F0),
        surfaceContainerHighest = Color(0xFFE0E0EA),
    )
    val dark = darkColorScheme(
        primary = Color(0xFF9C8CFF),
        onPrimary = Color(0xFF21164B),
        primaryContainer = Color(0xFF3F347B),
        onPrimaryContainer = Color(0xFFECE7FF),
        secondary = Color(0xFFA3B1CA),
        onSecondary = Color(0xFF253248),
        secondaryContainer = Color(0xFF354258),
        onSecondaryContainer = Color(0xFFE2E8F3),
        tertiary = Color(0xFF89C6B5),
        onTertiary = Color(0xFF12392F),
        tertiaryContainer = Color(0xFF274C41),
        onTertiaryContainer = Color(0xFFD0EFE3),
        error = Color(0xFFF2B8B5),
        onError = Color(0xFF601410),
        errorContainer = Color(0xFF8C1D18),
        onErrorContainer = Color(0xFFF9DEDC),
        background = Color(0xFF121318),
        onBackground = Color(0xFFE6E6EE),
        surface = Color(0xFF121318),
        onSurface = Color(0xFFE6E6EE),
        surfaceVariant = Color(0xFF33333F),
        onSurfaceVariant = Color(0xFFC8C5D3),
        outline = Color(0xFF938F9F),
        outlineVariant = Color(0xFF494652),
        inverseSurface = Color(0xFFE6E6EE),
        inverseOnSurface = Color(0xFF2E3038),
        inversePrimary = Color(0xFF5145D8),
        surfaceTint = Color(0xFF9C8CFF),
        scrim = Color(0xFF000000),
        surfaceDim = Color(0xFF121318),
        surfaceBright = Color(0xFF373740),
        surfaceContainerLowest = Color(0xFF0E0F13),
        surfaceContainerLow = Color(0xFF1A1B22),
        surfaceContainer = Color(0xFF20212A),
        surfaceContainerHigh = Color(0xFF272832),
        surfaceContainerHighest = Color(0xFF32333D),
    )
}
