blank_issues_enabled: false
contact_links:
  - name: BoxCast Discussions
    url: https://github.com/ashwkun/box.lore.android/discussions
    about: Ask questions, share ideas, and engage with the BoxCast community.
