#!/usr/bin/env bash
# Materialize non-secret local build files for Cursor Cloud Agents (and similar
# clean clones). Same google-services stub as
# .github/actions/write-ci-google-services — no Firebase / API secrets required.
#
# Idempotent. Safe to run as the cloud environment "install" / "update" command.
#
#   ./scripts/ci/write-cloud-agent-local-config.sh
#
# Does NOT write BOXCAST_*, PostHog, signing, or admin keys. BuildConfig fields
# default to empty strings when those properties are absent (see app/build.gradle.kts).
# GitHub merge-ci workflows write the same stub independently; Cursor Secrets are
# not needed for assembleDebug / unit checks.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT"

mkdir -p app

# Do not clobber a real developer google-services.json unless FORCE=1.
if [[ -f app/google-services.json && "${FORCE:-0}" != "1" ]]; then
  echo "Leaving existing app/google-services.json in place (set FORCE=1 to overwrite with stub)."
else
  python3 - <<'PY'
from pathlib import Path

path = Path("app/google-services.json")
path.write_text(
    """{
  "project_info": {
    "project_number": "0",
    "project_id": "boxlore-ci-unit-stub",
    "storage_bucket": "boxlore-ci-unit-stub.appspot.com"
  },
  "client": [
    {
      "client_info": {
        "mobilesdk_app_id": "1:0:android:0",
        "android_client_info": {
          "package_name": "cx.aswin.boxlore"
        }
      },
      "oauth_client": [],
      "api_key": [{ "current_key": "ci-unit-stub-not-a-real-key" }],
      "services": {
        "appinvite_service": {
          "other_platform_oauth_client": []
        }
      }
    }
  ],
  "configuration_version": "1"
}
""",
    encoding="utf-8",
)
path.chmod(0o600)
print(f"Wrote CI stub {path}")
PY
fi

# Prefer an already-configured SDK; otherwise common Linux / macOS defaults.
SDK_DIR="${ANDROID_SDK_ROOT:-${ANDROID_HOME:-}}"
if [[ -z "${SDK_DIR}" ]]; then
  if [[ -d "${HOME}/Android/Sdk" ]]; then
    SDK_DIR="${HOME}/Android/Sdk"
  elif [[ -d "${HOME}/Library/Android/sdk" ]]; then
    SDK_DIR="${HOME}/Library/Android/sdk"
  else
    SDK_DIR="${HOME}/Android/Sdk"
  fi
fi

# Preserve an existing local.properties (developer machine) unless FORCE=1.
if [[ -f local.properties && "${FORCE:-0}" != "1" ]]; then
  echo "Leaving existing local.properties in place (set FORCE=1 to overwrite)."
else
  cat > local.properties <<EOF
## Generated by scripts/ci/write-cloud-agent-local-config.sh — not for secrets.
sdk.dir=${SDK_DIR}
EOF
  chmod 600 local.properties
  echo "Wrote local.properties (sdk.dir=${SDK_DIR})"
fi

echo "Cloud/local stub config ready. No Cursor Secrets required for build + merge-ci unit tests."
