name: Qodo PR-Agent

on:
  pull_request:
    types: [opened, reopened, synchronize]
  issue_comment:
    types: [created]

jobs:
  pr_agent:
    name: Interactive Qodo PR-Agent
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: read
    steps:
      - name: Run PR Agent
        uses: the-pr-agent/pr-agent@d7e94bc27a8ad0456090a07e075cecd6e6459626
        env:
          CONFIG__MODEL: "groq/llama-3.3-70b-versatile"
          CONFIG__FALLBACK_MODELS: '["groq/llama-3.1-8b-instant"]'
          CONFIG__CUSTOM_MODEL_MAX_TOKENS: 32000
          GROQ_API_KEY: ${{ secrets.REVIEW_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
